name: Deploy PR to GitHub Pages

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy PR preview

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=22.18.0"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Deploy PR preview
        run: node tools/deploy-pr.js
        env:
          BRANCH_NAME: ${{ github.head_ref }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Deploy PR #${{ github.event.pull_request.number }} from ${{ github.head_ref }}"
          repository: gh-pages
          branch: gh-pages

      - name: Find comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Preview deployment ready!

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 Preview deployment ready!

            View your changes at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr/${{ env.SAFE_BRANCH_NAME }}/
          edit-mode: replace
