name: Format code

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  format:
    uses: ./.github/actions/run-npm-command.yml
    with:
      command: format
